### ISSUE TITLE
Query performance improvements

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#3852]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search, dashboards, alerts

### Description

Query performance is critical when it comes to dealing with large datasets. We could use multiple techniques to achieve better UX for users during query.

### Proposed solution

- [x]  Better default partition values `ZO_QUERY_GROUP_BASE_SPEED=768` , `ZO_QUERY_PARTITION_BY_SECS=1` #3853
- [x] Fast mode by partition key - #3844
- [x] Populate partial results - #3851
- [x] Query result caching Phase 1- #3859
- [ ] Query result caching Phase 2
- [x] Secondary Index @hengfeiyang  #3870
- [x] Fast mode for where clause @haohuaijin  #3862 
- [ ] Caching for value API @hengfeiyang 
- [x] Don't use full schema for ingestion @haohuaijin #3944 
- [ ] Code profiling 

### Alternatives considered

NA

**Comment by Abhishekraj8757** [comment]
@prabhatsharma is the openobserve product open source can i contribute to it.

**Comment by prabhatsharma** [comment]
> @prabhatsharma is the openobserve product open source can i contribute to it.

Yes. You can.
