### ISSUE TITLE
[Phase 2] Improve Inverted Index

### ISSUE THREAD

**Issue by uddhavdave** [openobserve/openobserve#5027]
### Description

We can further improve the inverted index performance by reducing the amount of data loaded in memory, caching the searcher results and reducing the scope of datafusion search.

### Proposed solution

Improve performance of Tantivy inverted index by
- [x] Caching most recently created tantivy files in memory. The ingestor/compactor should populate this cache on the querier which will allow the most recent data to be queried without network IO. @Loaki07 #5177  
- [x] Implement a ttv file footer cache in querier. Refer the footer for offsets of files needed to process the query and fetch the ttv file slice from object storage. @hengfeiyang  #5109 
- [x] Improve the File system Directory reader such that it can fetch only the required file slice from the ttv file instead of loading the whole file into memory. @hengfeiyang  #5056 #5130 
- [x] Reduce the scope of datafusion search by truncating the inverted index results based on the sql query. Only applicable on queries which have a limit on the size of results.  @haohuaijin Let tantivy only return topN matched row_id for each parquet( if the paruqet min_ts and max_ts in the search time range). #5149
- [x] optimizer select count(*) from table match_all() (if the paruqet min_ts and max_ts in the search time range) #5172
- [x] Reduce the filter of datafusion if the query only have match_all filter   @haohuaijin #5065
- [x] Test dump puffin to local directory then search it #5098
- [x] optimizer generate physical plan(now need 1.5s) https://github.com/openobserve/openobserve/pull/5088
- [x] skip index if the index return row_count is large than parquet 30% row_count(reduce generate access plan) #5154
- [x] match_all should support phrase queries (`AND` condition) #5154
- [x] Custom tokenizer support CamelCase split #5177
- [x] Show `Index size` in the stream page #5224
- [x] Support IN query in inverted index #5264

### others
- [ ] support negative match_all
- [ ] How to optimize histogram query with match_all
- [ ] create separate tantivy fields for full text search(str_match), we can use `match_all('error') and str_match(body, 'error')`
- [ ] Implement a subquery results cache for Inverted Index which will improve the performance of subsequent queries. 
- [x] support fuzzy query #5203
    ```rust
    let term = Term::from_field_text(field, "dataxxsion");
    let query:Box<dyn Query> = Box::new(FuzzyTermQuery::new(term, 2, true));
    ```
- [x] in TantivyCountExec, filter_file_list_by_tantivy_index function should always return true for is_add_filter_back. #5221

### test
name is the secondary index, age is not any index
- [x] match_all and name = 'a'；
- [x] (match_all OR match_all) AND match_all
- [x] only match_all
- [x] don't have match_all
- [x] match_all AND age > 10
- [x] (match_all OR name = 'a') And age > 10
- [x] match_all OR name = 'a'
- [x] Test tantivy on super cluster #5221
- [x] Test empty data for create tantivy index #5202
- [x] #5274
- [x] #5287

### Alternatives considered

None
