### ISSUE TITLE
Search using web-sockets & result_cache_v2

### ISSUE THREAD

**Issue by Loaki07** [openobserve/openobserve#5188]
### Which OpenObserve functionalities are relevant/related to the feature request?

Search

### Description

Implement web-sockets for all search queries. 

### Tasks
- [x] search context params to be added to request payload
- [x] modify search response to include `order_by` for every response
- [x] send `is_partial` & `fn_error` if search fails in between processing a single request
- [x] cache request managent in dashboards needs to be migrated to server for ws
- [x] new error schema with `code`, `error_detail`, `message`
- [x] In dashboards if histogram interval is auto, the server needs to determine the interval and apply them to all the internal search queries
- [x] config variable to enable/disable web-sockets
- [x] handle cache response based on `order_by` 
- [x] calc `result_cache_ratio`
- [x] handle req size and trim the results for cache hits 
- [x] web-sockets audit is currently disabled, new mechanism for auditing
- [x] bug: dashboards long duration queries is returning only only 1 response
- [x] handle pagination for cache when request `from` is specified
- [x] bug: search error needs to be sent to UI
- [x] support for query time vrl functions
- [x] disable `max_query_limit` for `Alerts`
- [x] all dashboard queries will have order_by as `desc`
- [x] fix: on cancel even all searches to be canceled 
- [x] fix: limit queries
- [x] bug: `Websocket closed before connection is established`
- [x] alert url to include search_event_type
- [x] `cached_ratio` is greater an 100 for results cache responses
- [x] enable `max_query_limit` for `Alerts` -- need confirmation
- [x] cache `is_partial` errors only when its range error
- [x] fix: vrl
- [x] fix: scan_size should be 0 for cached responses
- [x] new_start_time & new_end_time for non-cache responses
- [x] abnormal ws close(1006) when close reason's description is too long where it should be sending (1011) [link](https://github.com/actix/actix-extras/discussions/489)

### Alternatives considered

None
