### ISSUE TITLE
refactor and migrate `Destinations` & `Templates`

### ISSUE THREAD

**Issue by taimingl** [openobserve/openobserve#5336]
- [x] migrate `templates` from meta to its own table #5393 
- [x] migrate `destinations` from meta to its own table #5397 
- [x] refactor the data structure model to incorporate business unit #5397
