### ISSUE TITLE
Optimize metrics performance

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#5456]
### Description

- [x] Parallels data point calculation #5466 
- [x] Use streaming collection for datafusion to avoid OOM (We load all the data into memory at once) #5584 
- [x] Histogram data is wrong #5480
- [x] Align data point time #5485
- [x] Align auto-step #5485
- [x] Fix search data with wal, need check the minimal time range #5504 
- [x] Remove `exemplars` from query API #5511 
- [x] Add API `query_exemplars` https://prometheus.io/docs/prometheus/latest/querying/api/#querying-exemplars
- [x] index for PromQL #5552
- [x] Add cache and performance improve #5656 #5729 #5794 
- [x] Add Auto-Downsampling   #5793
- [x] Recording rules
- [x] impl work group like log #9400
- [ ] impl query_manager like log
- [x] impl super cluster like log #9225
- [x] ~~impl background search job like log~~
