### ISSUE TITLE
Websockets Phase 2

### ISSUE THREAD

**Issue by Loaki07** [openobserve/openobserve#5497]
## Tasks:
- [ ] re-use active sessions, to reduce the number of new connections by client
- [ ] cache results upto the point of cancel 
- [ ] if search results are partial then write it to separate cache, since if limited results are written to single cache the results could vary if `max_query_range` is modified
- [ ] rate limit for `WS_SESSIONS`
- [ ] check cache for the partitions as well
- [ ] Search Around (need confirmation)
- [ ] Multi Stream Search (need confirmation)
- [ ] limit is not honored in ws
- [ ] limit query return results in descending order/ api returns in asc order

### Proposed solution

-

### Alternatives considered

-

**Comment by Loaki07** [comment]
Deprecated: Since ws v2 is already implemented. 
https://github.com/openobserve/openobserve/pull/6404
